modules:
  - postgres
  - mariadb
  - samba_dc
  - nextcloud
  - collabora
  - meshcentral

global:
  domain: nas.test
  email: admin@nas.test
  data_path: ./.anas-test/data
  timezone: Asia/Shanghai
  dns_provider: manual
  default_service_root_password: change-me-now

env:
  BASICAUTH_USER: admin
