modules:
  - traefik
  - lego
  - samba_dc
  - ddns
  - eturnal
  - netbird
  - freeradius

global:
  domain: nas.test
  email: admin@nas.test
  timezone: Asia/Shanghai
  dns_provider: manual
  default_service_root_password: change-me-now

env:
  BASICAUTH_USER: admin
