modules:
  - samba_dc
  - samba_fs
  - postgres
  - llng
  - nextcloud
  - collabora
  - meshcentral
  - netbird
  - lam

global:
  domain: nas.example.com
  email: admin@example.com
  data_path: ./data
  timezone: Asia/Shanghai
  dns_provider: manual
  default_root_password: change-me-now

env:
  BASICAUTH_USER: admin
