Dir "/";
Dir::Etc "/etc/anas/incus-apt";
Dir::Etc::main "apt.conf.empty";
Dir::Etc::parts "apt.conf.d";
Dir::Etc::sourcelist "anas-incus-empty.list";
Dir::Etc::sourceparts "sources.list.d/ubuntu-26.04";
Dir::Etc::preferences "preferences";
Dir::Etc::preferencesparts "preferences.d/ubuntu-26.04";
Dir::State::lists "/var/lib/anas/incus-apt/lists";
Dir::Cache::archives "/var/cache/anas/incus-apt/archives";
Dir::Cache::srcpkgcache "/var/cache/anas/incus-apt/srcpkgcache.bin";
Dir::Cache::pkgcache "/var/cache/anas/incus-apt/pkgcache.bin";
DPkg::Pre-Install-Pkgs "";
DPkg::Post-Invoke "";
APT::Update::Post-Invoke "";
APT::Update::Post-Invoke-Success "";
APT::Get::List-Cleanup "0";
Acquire::AllowInsecureRepositories "false";
Acquire::AllowDowngradeToInsecureRepositories "false";
