// REQUIREMENTS: CONSOLE-R-126 CONSOLE-R-128
import type { components } from "./schema"
import type { Locale } from "../i18n/messages"

type Problem = components["schemas"]["Problem"]

const problemMessages = {
  zh: {
    request_failed: "请求失败，请检查网络连接后重试。",
    forbidden: "当前会话无权执行此操作。",
    authorization_unavailable: "授权服务暂时不可用。",
    invalid_host: "当前访问地址不在控制台允许列表中。",
    invalid_query: "请求查询参数无效。",
    unknown_query_parameter: "请求包含不支持的查询参数。",
    unexpected_body: "此请求不接受请求体。",
    method_not_allowed: "此地址不支持当前请求方法。",
    invalid_bootstrap_token: "引导令牌无效或已过期，请在 NAS 终端重新生成。",
    invalid_credentials: "本地管理员密码不正确。",
    login_rate_limited: "登录尝试过于频繁，请稍后再试。",
    authentication_rate_limited: "认证尝试过于频繁，请稍后再试。",
    csrf_mismatch: "页面凭据已失效，请刷新页面后重试。",
    origin_mismatch: "请求来源不符合当前控制台地址。",
    invalid_origin: "当前控制台地址无效。",
    unauthenticated: "认证已失效，请重新登录。",
    enrollment_unauthorized: "注册凭据无效或已过期，请重新开始注册。",
    enrollment_forbidden: "注册请求未通过安全校验。",
    enrollment_unavailable: "注册服务暂时不可用。",
    enrollment_certificate_not_ready: "受信任的 HTTPS 证书尚未就绪，请稍后重试。",
    enrollment_target_invalid: "HTTPS 注册目标无效。",
    owner_enrollment_failed: "无法创建首个本地管理员，请检查密码后重试。",
    authentication_unavailable: "本地认证服务暂时不可用。",
    state_unavailable: "无法读取控制台运行状态。",
    certificate_unavailable: "无法读取控制台证书状态。",
    random_unavailable: "无法生成安全凭据，请稍后重试。",
    invalid_json: "请求内容无效。",
    request_too_large: "提交内容过大。",
    unsupported_media_type: "提交格式不受支持。",
    not_found: "当前状态下此操作不可用，请刷新页面。",
    password_mismatch: "两次输入的密码不一致。",
    enrollment_session_missing: "未找到 HTTPS 注册会话，请使用新的引导令牌继续。",
    workspace_not_found: "工作区不存在或未向 anasd 注册。",
    config_candidate_invalid: "配置草稿无效，请检查字段后重试。",
    config_unavailable: "工作区配置暂时不可用。",
    config_validator_invalid: "配置版本标识无效，请重新读取。",
    config_boolean_invalid: "布尔字段必须是 true 或 false。",
    config_integer_invalid: "整数必须是浏览器可安全表示的十进制整数。",
    config_sensitive_value_required: "选择设置敏感字段时必须输入新值。",
    config_sensitive_operation_invalid: "敏感字段操作无效。",
    config_field_read_only: "草稿修改了控制台不可编辑的字段。",
    config_precondition_failed: "配置已被其他操作修改，请重新读取后再编辑。",
    config_precondition_required: "缺少保存配置所需的版本条件，请重新读取。",
    config_response_invalid: "服务器返回的配置版本信息不完整，请重新读取。",
    config_schema_unavailable: "暂时无法读取配置 schema。",
    config_projection_unavailable: "暂时无法生成公开配置视图。",
    config_state_invalid: "服务器上的当前配置无效，需要在终端修复。",
    config_validation_unavailable: "配置验证服务暂时不可用。",
    config_lock_unavailable: "配置正被其他操作占用，请稍后重试。",
    config_recovery_required: "配置提交状态不确定，需要先在终端完成恢复。",
    secrets_unavailable: "敏感配置存储暂时不可用。",
    audit_unavailable: "审计日志暂时不可用，配置未保存。",
    runtime_lock_unavailable: "工作区正被其他运行操作占用，请稍后重试。",
    request_canceled: "请求已取消，请重试。",
    deadline_exceeded: "请求超时，请稍后重试。",
    deployment_unavailable: "部署计划服务暂时不可用。",
    plan_binding_invalid: "服务器返回的计划绑定无效。",
    plan_response_invalid: "服务器返回的计划确认与计划内容不一致。",
    step_up_required: "此操作需要重新验证本地管理员密码。",
    step_up_invalid: "重新认证证明已过期、已使用或不再匹配当前计划。",
    step_up_source_invalid: "当前认证来源不能执行本地重新认证。",
    recent_auth_required: "身份服务认证已超过 5 分钟，请重新登录身份服务后再试。",
    step_up_consumed: "重新认证证明已被使用，请重新生成计划。",
    confirmation_required: "缺少完整的计划确认，请重新生成计划。",
    confirmation_unavailable: "暂时无法签发计划确认。",
    confirmation_invalid: "计划确认已过期、已使用或不再匹配当前状态。",
    confirmation_consumed: "计划确认已被使用，请重新生成计划。",
    idempotency_key_required: "提交变更任务缺少幂等键。",
    idempotency_key_invalid: "变更任务的幂等键无效。",
    idempotency_conflict: "同一幂等键已用于不同的变更请求。",
    apply_request_invalid: "Apply 请求缺少必需的计划绑定。",
    invalid_snapshot_policy: "快照选项互相冲突。",
    job_capacity_reached: "任务队列已满，请稍后重试。",
    job_conflict: "工作区已有冲突任务或需要先完成补偿检查。",
    jobs_unavailable: "持久任务服务暂时不可用。",
    job_not_found: "任务不存在或当前会话不可见。",
    module_commands_unavailable: "Module 命令服务暂时不可用。",
    module_command_digest_required: "请先读取命令详情并携带其 command_digest。",
    module_command_changed: "命令描述符已变化，请重新读取命令后再执行。",
    module_command_unavailable: "该 Module 命令在当前部署下不可用。",
    module_command_not_found: "Module 命令不存在。",
    module_command_busy: "工作区正被占用，命令未能取得运行时锁。",
    module_command_confirmation_required: "破坏性命令需要先完成重新认证。",
    module_command_invalid_parameter: "命令参数无效。",
    module_command_timeout: "Module 命令执行超时。",
    module_command_protocol_error: "Module 命令返回了无效输出。",
    module_command_failed: "Module 命令执行失败。",
    job_cancel_unavailable: "任务取消服务暂时不可用。",
    lifecycle_request_invalid: "生命周期请求无效。",
    lifecycle_action_not_found: "不支持该生命周期操作。",
    lifecycle_preview_changed: "部署或依赖链已变化，请重新生成预览。",
    lifecycle_confirmation_required: "请先确认将实际操作的 Module 依赖链。",
    rollback_request_invalid: "回滚请求无效。",
    rollback_preview_changed: "回滚目标或部署已变化，请重新生成预览。",
    rollback_confirmation_required: "请先确认回滚影响后再继续。",
    principal_unavailable: "当前会话身份不可用，请重新登录。",
    invalid_job_id: "任务 ID 无效。",
    invalid_cursor: "分页游标无效或已过期。",
    invalid_limit: "分页数量无效。",
    invalid_last_event_id: "任务事件游标无效。",
    event_stream_required: "任务事件请求必须接受 SSE。",
    event_gap: "部分较早的任务事件已被清理，请重新读取任务详情。",
    sse_connection_limit: "实时任务连接已满，请稍后重试。",
    streaming_unsupported: "当前服务链路不支持实时任务流。",
    job_event_invalid: "收到的任务事件无效，实时跟踪已停止。",
    plan_changed: "配置或部署计划已变化，请重新生成计划。",
    guarded_changes: "Apply 被守卫变更阻止；请查看页面列出的每一项。",
    apply_failed: "部署 apply 失败。",
    daemon_shutdown: "守护进程关闭，任务已中断并需要检查补偿状态。",
    console_asset_unavailable: "控制台静态资源暂时不可用。",
    response_encoding_failed: "服务器无法编码响应。",
    invalid_precondition: "请求的版本条件无效。",
    invalid_deployment_id: "部署 ID 无效。",
    deployment_missing: "目标部署不存在。",
    deployment_not_ready: "目标部署尚未准备好。",
    state_unreadable: "无法读取工作区运行状态。",
    secrets_unreadable: "无法读取敏感配置存储。",
    config_requires_import: "配置中仍有未导入的敏感值，请先在终端导入。",
    contract_root_invalid: "Module 契约目录无效。",
    contract_invalid: "Module 契约无效。",
    resolution_failed: "Module 依赖解析失败。",
    version_conflict: "Module 版本约束冲突。",
    lock_invalid: "Module 锁文件无效。",
    plan_unavailable: "部署计划服务不可用。",
    apply_unavailable: "部署 Apply 服务不可用。",
    plan_canceled: "部署计划已取消。",
    apply_canceled: "部署 Apply 已取消。",
    plan_digest_failed: "无法生成部署计划摘要。",
    image_rebuild_required: "此变更需要重新构建镜像。",
    step_up_request_invalid: "重新认证的操作或目标无效。",
    invalid_handoff_form: "HTTPS 注册表单无效。",
    handoff_credentials_forbidden: "HTTPS 注册交换携带了禁止的环境凭据。",
    handoff_target_mismatch: "HTTPS 注册目标与签发绑定不一致。",
    config_not_managed: "当前配置不是受管配置，需先在终端修复。",
    config_missing: "工作区缺少配置文件。",
    config_invalid: "当前期望配置无效。",
    module_root_missing: "工作区缺少固定的 Module 视图。",
    module_root_invalid: "工作区的 Module 视图无效。",
    module_response_invalid: "服务器返回的 Module 状态不完整，请重新读取。",
    module_management_unavailable: "Module 管理服务暂时不可用。",
    module_view_unavailable: "工作区的 Module 视图暂时不可用。",
    module_source_unavailable: "Module 目录源暂时不可用。",
    module_cache_corrupt: "Module 缓存损坏，需要在终端修复。",
    module_sync_failed: "Module 同步失败，请查看持久任务详情。",
    module_update_failed: "Module 更新失败，请查看持久任务详情。",
    module_config_failed: "Module 期望配置变更失败。",
    module_lock_mismatch: "Module 安装内容与锁文件不匹配。",
    module_not_found: "Module 不在当前工作区视图或目录中。",
    module_not_selected: "Module 尚未在期望配置中选择。",
    module_name_invalid: "Module 名称无效。",
    module_update_request_invalid: "Module 同步或更新请求无效。",
    module_action_not_found: "Module 操作不存在。",
    workspace_id_invalid: "工作区 ID 无效。",
    workspace_id_required: "必须选择工作区。",
    lock_stale: "Module 锁与当前配置不一致，请先更新锁。",
    network_namespace_requires_tty: "当前配置需要交互式 sudo/nsenter，不能由 daemon apply。",
    maintenance_response_invalid: "服务器返回的维护数据与当前选择不一致，请重新读取。",
    maintenance_unavailable: "快照、备份与账户维护服务暂时不可用。",
    snapshot_label_invalid: "快照标签无效。",
    snapshot_missing: "目标快照不存在。",
    snapshot_pinned: "快照已固定；生成删除命令前必须明确选择 force。",
    snapshot_action_not_found: "快照操作不存在。",
    snapshot_create_failed: "快照创建失败，请查看持久任务详情。",
    snapshot_update_failed: "快照元数据更新失败，请查看持久任务详情。",
    snapshot_verify_failed: "快照验证失败，请查看持久任务详情。",
    backup_target_invalid: "备份目标 ID 无效。",
    backup_target_not_found: "备份目标未在 anasd 服务配置中注册。",
    backup_plan_unavailable: "暂时无法计算备份计划。",
    backup_plan_changed: "备份计划已变化，请重新计算后再生成命令。",
    local_admin_target_invalid: "本地管理员目标无效。",
    local_admin_missing: "目标本地管理员不存在。",
    local_admin_state_unreadable: "无法读取本地管理员状态。",
    local_admin_random_failed: "无法生成随机管理员密码。",
    local_admin_rotate_failed: "本地管理员随机轮换失败，请查看持久任务详情。",
    secret_missing: "目标本地管理员没有可显示的已生成凭据。",
    terminal_action_target_invalid: "终端操作的目标类型或 ID 无效。",
    terminal_action_option_invalid: "终端操作包含不适用的选项。",
    terminal_action_operation_invalid: "终端操作不在允许的枚举中。",
    userdata_not_captured: "所选快照没有捕获 userdata/。",
    internal_error: "服务器发生内部错误。",
  },
  en: {
    request_failed: "The request failed. Check the network connection and try again.",
    forbidden: "This session is not permitted to perform the operation.",
    authorization_unavailable: "Authorization is temporarily unavailable.",
    invalid_host: "This address is not allowed by the console configuration.",
    invalid_query: "The request query is invalid.",
    unknown_query_parameter: "The request contains an unsupported query parameter.",
    unexpected_body: "This request does not accept a body.",
    method_not_allowed: "This endpoint does not support the request method.",
    invalid_bootstrap_token: "The bootstrap token is invalid or expired. Generate a new one on the NAS.",
    invalid_credentials: "The local administrator password is incorrect.",
    login_rate_limited: "Too many login attempts. Try again later.",
    authentication_rate_limited: "Too many authentication attempts. Try again later.",
    csrf_mismatch: "The page credential has expired. Refresh the page and try again.",
    origin_mismatch: "The request origin does not match this console address.",
    invalid_origin: "This console address is invalid.",
    unauthenticated: "Authentication has expired. Sign in again.",
    enrollment_unauthorized: "The enrollment credential is invalid or expired. Start enrollment again.",
    enrollment_forbidden: "The enrollment request failed its security checks.",
    enrollment_unavailable: "Enrollment is temporarily unavailable.",
    enrollment_certificate_not_ready: "The trusted HTTPS certificate is not ready. Try again shortly.",
    enrollment_target_invalid: "The HTTPS enrollment target is invalid.",
    owner_enrollment_failed: "The first local administrator could not be created. Check the password and try again.",
    authentication_unavailable: "Local authentication is temporarily unavailable.",
    state_unavailable: "The console runtime state could not be read.",
    certificate_unavailable: "The console certificate state could not be read.",
    random_unavailable: "A secure credential could not be generated. Try again later.",
    invalid_json: "The request content is invalid.",
    request_too_large: "The submitted content is too large.",
    unsupported_media_type: "The submitted format is not supported.",
    not_found: "This action is unavailable in the current state. Refresh the page.",
    password_mismatch: "The passwords do not match.",
    enrollment_session_missing: "No HTTPS enrollment session was found. Continue with a new bootstrap token.",
    workspace_not_found: "The workspace does not exist or is not registered with anasd.",
    config_candidate_invalid: "The configuration draft is invalid. Check the fields and try again.",
    config_unavailable: "The workspace configuration is temporarily unavailable.",
    config_validator_invalid: "The configuration version is invalid. Reload it.",
    config_boolean_invalid: "A boolean field must be true or false.",
    config_integer_invalid: "An integer must be a decimal value that the browser can represent safely.",
    config_sensitive_value_required: "Enter a new value when setting a sensitive field.",
    config_sensitive_operation_invalid: "The sensitive-field operation is invalid.",
    config_field_read_only: "The draft changes a field that the console cannot edit.",
    config_precondition_failed: "The configuration changed elsewhere. Reload it before editing again.",
    config_precondition_required: "The configuration version required for saving is missing. Reload it.",
    config_response_invalid: "The server returned incomplete configuration version information. Reload it.",
    config_schema_unavailable: "The configuration schema is temporarily unavailable.",
    config_projection_unavailable: "The public configuration view is temporarily unavailable.",
    config_state_invalid: "The current server configuration is invalid and must be repaired from the terminal.",
    config_validation_unavailable: "Configuration validation is temporarily unavailable.",
    config_lock_unavailable: "Another operation is using the configuration. Try again shortly.",
    config_recovery_required: "The configuration commit is indeterminate and must be recovered from the terminal first.",
    secrets_unavailable: "The sensitive configuration store is temporarily unavailable.",
    audit_unavailable: "The audit journal is unavailable, so the configuration was not saved.",
    runtime_lock_unavailable: "Another runtime operation is using this workspace. Try again shortly.",
    request_canceled: "The request was canceled. Try again.",
    deadline_exceeded: "The request timed out. Try again later.",
    deployment_unavailable: "Deployment planning is temporarily unavailable.",
    plan_binding_invalid: "The server returned an invalid plan binding.",
    plan_response_invalid: "The server confirmation does not match the returned plan.",
    step_up_required: "Re-enter the local administrator password for this action.",
    step_up_invalid: "The step-up proof expired, was consumed, or no longer matches this plan.",
    step_up_source_invalid: "This authentication source cannot use local step-up.",
    recent_auth_required: "The identity-provider authentication is older than five minutes. Sign in through the identity service again.",
    step_up_consumed: "The step-up proof was consumed. Generate a new plan.",
    confirmation_required: "A complete plan confirmation is required. Generate a new plan.",
    confirmation_unavailable: "A plan confirmation cannot be issued right now.",
    confirmation_invalid: "The plan confirmation expired, was consumed, or no longer matches current state.",
    confirmation_consumed: "The plan confirmation was consumed. Generate a new plan.",
    idempotency_key_required: "The change job is missing its idempotency key.",
    idempotency_key_invalid: "The change-job idempotency key is invalid.",
    idempotency_conflict: "This idempotency key belongs to a different change request.",
    apply_request_invalid: "The apply request is missing a required plan binding.",
    invalid_snapshot_policy: "The snapshot options conflict.",
    job_capacity_reached: "The job queue is full. Try again later.",
    job_conflict: "The workspace has a conflicting job or requires a compensation check first.",
    jobs_unavailable: "The durable job service is temporarily unavailable.",
    job_not_found: "The job does not exist or is not visible to this session.",
    module_commands_unavailable: "The Module command service is temporarily unavailable.",
    module_command_digest_required: "Read the command detail first and send its command_digest.",
    module_command_changed: "The command descriptor changed. Read the command again before running it.",
    module_command_unavailable: "This Module command is not available in the current deployment.",
    module_command_not_found: "The Module command does not exist.",
    module_command_busy: "The workspace is busy, so the command could not take the runtime lock.",
    module_command_confirmation_required: "A destructive command requires re-authentication first.",
    module_command_invalid_parameter: "A command parameter is invalid.",
    module_command_timeout: "The Module command timed out.",
    module_command_protocol_error: "The Module command returned invalid output.",
    module_command_failed: "The Module command failed.",
    job_cancel_unavailable: "Job cancellation is temporarily unavailable.",
    lifecycle_request_invalid: "The lifecycle request is invalid.",
    lifecycle_action_not_found: "That lifecycle action is not supported.",
    lifecycle_preview_changed: "The deployment or dependency chain changed. Generate a new preview.",
    lifecycle_confirmation_required: "Confirm the module dependency chain that will actually be operated on.",
    rollback_request_invalid: "The rollback request is invalid.",
    rollback_preview_changed: "The rollback target or deployment changed. Generate a new preview.",
    rollback_confirmation_required: "Confirm the rollback impact before continuing.",
    principal_unavailable: "The session identity is unavailable. Sign in again.",
    invalid_job_id: "The job ID is invalid.",
    invalid_cursor: "The pagination cursor is invalid or expired.",
    invalid_limit: "The pagination limit is invalid.",
    invalid_last_event_id: "The job-event cursor is invalid.",
    event_stream_required: "The job-event request must accept SSE.",
    event_gap: "Some older job events were pruned. Reload the job detail.",
    sse_connection_limit: "The live-job connection limit was reached. Try again later.",
    streaming_unsupported: "This service path does not support live job streaming.",
    job_event_invalid: "An invalid job event was received, so live tracking stopped.",
    plan_changed: "Configuration or the deployment plan changed. Generate a new plan.",
    guarded_changes: "Guarded changes blocked apply. Review every item shown on this page.",
    apply_failed: "Deployment apply failed.",
    daemon_shutdown: "The daemon stopped, interrupting the job and requiring a compensation check.",
    console_asset_unavailable: "Console assets are temporarily unavailable.",
    response_encoding_failed: "The server could not encode its response.",
    invalid_precondition: "The request version condition is invalid.",
    invalid_deployment_id: "The deployment ID is invalid.",
    deployment_missing: "The target deployment does not exist.",
    deployment_not_ready: "The target deployment is not ready.",
    state_unreadable: "The workspace runtime state could not be read.",
    secrets_unreadable: "The sensitive configuration store could not be read.",
    config_requires_import: "The configuration still contains unimported secrets. Import them from the terminal.",
    contract_root_invalid: "The Module contract directory is invalid.",
    contract_invalid: "A Module contract is invalid.",
    resolution_failed: "Module dependency resolution failed.",
    version_conflict: "Module version constraints conflict.",
    lock_invalid: "The Module lock file is invalid.",
    plan_unavailable: "Deployment planning is unavailable.",
    apply_unavailable: "Deployment apply is unavailable.",
    plan_canceled: "Deployment planning was canceled.",
    apply_canceled: "Deployment apply was canceled.",
    plan_digest_failed: "The deployment plan digest could not be generated.",
    image_rebuild_required: "This change requires an image rebuild.",
    step_up_request_invalid: "The step-up action or target is invalid.",
    invalid_handoff_form: "The HTTPS enrollment form is invalid.",
    handoff_credentials_forbidden: "The HTTPS enrollment exchange included forbidden ambient credentials.",
    handoff_target_mismatch: "The HTTPS enrollment target does not match its issued binding.",
    config_not_managed: "The current configuration is not managed and must be repaired from the terminal.",
    config_missing: "The workspace configuration file is missing.",
    config_invalid: "The current desired configuration is invalid.",
    module_root_missing: "The workspace has no pinned Module view.",
    module_root_invalid: "The workspace Module view is invalid.",
    module_response_invalid: "The server returned incomplete Module state. Reload it.",
    module_management_unavailable: "Module management is temporarily unavailable.",
    module_view_unavailable: "The workspace Module view is temporarily unavailable.",
    module_source_unavailable: "The Module catalog source is temporarily unavailable.",
    module_cache_corrupt: "The Module cache is corrupt and must be repaired from the terminal.",
    module_sync_failed: "Module synchronization failed. Review the durable job detail.",
    module_update_failed: "Module update failed. Review the durable job detail.",
    module_config_failed: "The Module desired-configuration change failed.",
    module_lock_mismatch: "The installed Module content does not match the lock.",
    module_not_found: "The Module is not in the current workspace view or catalog.",
    module_not_selected: "The Module is not selected in desired configuration.",
    module_name_invalid: "The Module name is invalid.",
    module_update_request_invalid: "The Module sync or update request is invalid.",
    module_action_not_found: "The Module action does not exist.",
    workspace_id_invalid: "The workspace ID is invalid.",
    workspace_id_required: "A workspace must be selected.",
    lock_stale: "The Module lock no longer matches configuration. Update the lock first.",
    network_namespace_requires_tty: "This configuration needs interactive sudo/nsenter and cannot be applied by the daemon.",
    maintenance_response_invalid: "The maintenance response does not match the current selection. Reload it.",
    maintenance_unavailable: "Snapshot, backup, and account maintenance is temporarily unavailable.",
    snapshot_label_invalid: "The snapshot label is invalid.",
    snapshot_missing: "The target snapshot does not exist.",
    snapshot_pinned: "The snapshot is pinned. Explicitly select force before generating its delete command.",
    snapshot_action_not_found: "The snapshot action does not exist.",
    snapshot_create_failed: "Snapshot creation failed. Review the durable job detail.",
    snapshot_update_failed: "Snapshot metadata update failed. Review the durable job detail.",
    snapshot_verify_failed: "Snapshot verification failed. Review the durable job detail.",
    backup_target_invalid: "The backup target ID is invalid.",
    backup_target_not_found: "The backup target is not registered in the anasd service configuration.",
    backup_plan_unavailable: "The backup plan cannot be calculated right now.",
    backup_plan_changed: "The backup plan changed. Recalculate it before generating the command.",
    local_admin_target_invalid: "The local-administrator target is invalid.",
    local_admin_missing: "The target local administrator does not exist.",
    local_admin_state_unreadable: "The local-administrator state cannot be read.",
    local_admin_random_failed: "A random administrator password could not be generated.",
    local_admin_rotate_failed: "Random local-administrator rotation failed. Review the durable job detail.",
    secret_missing: "The target local administrator has no generated credential to reveal.",
    terminal_action_target_invalid: "The terminal action has an invalid target type or ID.",
    terminal_action_option_invalid: "The terminal action contains an option that does not apply.",
    terminal_action_operation_invalid: "The terminal action is not in the allowed enumeration.",
    userdata_not_captured: "The selected snapshot did not capture userdata/.",
    internal_error: "The server encountered an internal error.",
  },
} as const

export type KnownProblemCode = keyof (typeof problemMessages)["zh"]

export class APIProblemError extends Error {
  readonly code: string

  constructor(value: unknown) {
    const code = problemCode(value)
    super(code)
    this.name = "APIProblemError"
    this.code = code
  }
}

export function problemCode(value: unknown): string {
  if (typeof value === "object" && value !== null) {
    const code = (value as Partial<Problem>).code
    if (typeof code === "string" && code.length > 0) return code
  }
  return "request_failed"
}

export function problemMessage(locale: Locale, code: string): string {
  const translated = (problemMessages[locale] as Record<string, string>)[code]
  return translated ?? code
}

export function errorMessage(locale: Locale, value: unknown): string {
  return problemMessage(locale, value instanceof APIProblemError ? value.code : problemCode(value))
}

export { problemMessages }
