package dns

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// Projection is one engine's slice of the registry, rendered as a
// self-contained Go source file for that engine's cask bundle.
//
// A cask hook is a standalone program inside a bundle that must stay usable
// after the bundle is copied away from this repository, so it cannot import
// the registry package. Copying the data instead of the dependency is the
// trade-off that keeps bundles distributable; the contract test is what stops
// the copy from drifting.
type Projection struct {
	Engine string
	Path   string
	Source []byte
}

// caskFor maps an engine to the cask bundle that receives its projection. It
// is one-to-one today because each engine is exactly one cask, and keeping the
// mapping explicit means adding a second lego-like cask does not silently
// inherit lego's table.
var caskFor = map[string]string{
	EngineLego:        "lego",
	EngineDDNSGo:      "ddns_go",
	EngineDDNSUpdater: "ddns_updater",
}

// Projections renders every engine's table, in a stable order.
func (r *Registry) Projections() ([]Projection, error) {
	engines := append([]string{}, knownEngines...)
	sort.Strings(engines)
	out := make([]Projection, 0, len(engines))
	for _, engine := range engines {
		source, err := r.project(engine)
		if err != nil {
			return nil, err
		}
		out = append(out, Projection{
			Engine: engine,
			Path:   "casks/mods/" + caskFor[engine] + "/hook/dns_registry_gen.go",
			Source: source,
		})
	}
	return out, nil
}

func (r *Registry) project(engine string) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/gen-dns-registry from internal/dns/providers.yml. DO NOT EDIT.\n\n")
	b.WriteString("package main\n\n")
	fmt.Fprintf(&b, `// dnsPlatform describes how this cask addresses one DNS vendor. IDKey,
// SecretKey and ExtKey name the credential this engine puts in each of its
// configuration slots; an empty string means the slot is unused. The keys are
// canonical vendor names -- the runner materialises them under this cask's own
// env prefix, so a hook reads %q + "_" + key.
type dnsPlatform struct {
	Name     string
	Provider string
	IDKey    string
	SecretKey string
	ExtKey   string
	Required []string
}

`, strings.ToUpper(caskFor[engine]))

	platforms := []*Platform{}
	for i := range r.Platforms {
		if r.Platforms[i].Supports(engine) {
			platforms = append(platforms, &r.Platforms[i])
		}
	}
	sort.Slice(platforms, func(i, j int) bool { return platforms[i].Name < platforms[j].Name })

	b.WriteString("var dnsPlatforms = map[string]dnsPlatform{\n")
	for _, p := range platforms {
		support := p.Engines[engine]
		slots := map[string]string{}
		for _, cred := range support.Credentials {
			slots[cred.Role] = cred.Key
		}
		fmt.Fprintf(&b, "\t%s: {Name: %s, Provider: %s, IDKey: %s, SecretKey: %s, ExtKey: %s, Required: %s},\n",
			strconv.Quote(p.Name), strconv.Quote(p.Name), strconv.Quote(support.Provider),
			strconv.Quote(slots[RoleID]), strconv.Quote(slots[RoleSecret]), strconv.Quote(slots[RoleExt]),
			goStringSlice(p.RequiredKeys(engine)))
	}
	b.WriteString("}\n\n")

	// Aliases are flattened into the projection so a hook resolves the same
	// user input the runner does, without carrying the normalisation rules.
	aliases := map[string]string{}
	for name, p := range r.byName {
		if !p.Supports(engine) || name == p.Name {
			continue
		}
		aliases[name] = p.Name
	}
	keys := make([]string, 0, len(aliases))
	for k := range aliases {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	b.WriteString("// dnsPlatformAliases maps every accepted spelling to a canonical name.\n")
	b.WriteString("var dnsPlatformAliases = map[string]string{\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "\t%s: %s,\n", strconv.Quote(k), strconv.Quote(aliases[k]))
	}
	b.WriteString("}\n\n")

	b.WriteString(`// lookupDNSPlatform resolves a configured platform name, accepting any
// registered alias and treating hyphen and underscore as equivalent.
func lookupDNSPlatform(name string) (dnsPlatform, bool) {
	key := strings.ReplaceAll(strings.ToLower(strings.TrimSpace(name)), "-", "_")
	if canonical, ok := dnsPlatformAliases[key]; ok {
		key = canonical
	}
	p, ok := dnsPlatforms[key]
	return p, ok
}

// supportedDNSPlatforms lists what this cask can address, for error messages.
func supportedDNSPlatforms() []string {
	out := make([]string, 0, len(dnsPlatforms))
	for name := range dnsPlatforms {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}
`)

	source := strings.Replace(b.String(), "package main\n\n",
		"package main\n\nimport (\n\t\"sort\"\n\t\"strings\"\n)\n\n", 1)
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("dns registry: generated source for %s does not parse: %w", engine, err)
	}
	return formatted, nil
}

func goStringSlice(items []string) string {
	if len(items) == 0 {
		return "nil"
	}
	var b bytes.Buffer
	b.WriteString("[]string{")
	for i, item := range items {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(item))
	}
	b.WriteString("}")
	return b.String()
}
