services:
  anas_lego:
    build:
      context: ./lego
      network: ${DOCKER_BUILD_NETWORK:-default}
      args:
        - CHINESE_BUILD_SPEEDUP
        - APK_MIRROR_URL
        - DOCKER_HUB_REGISTRY
    container_name: ${CONTAINER_PREFIX}lego
    image: ${ANAS_IMAGE_REGISTRY:-ghcr.io/anas-project}/anas-lego:5.3.1-r3
    restart: unless-stopped
    volumes:
      - "${LEGO_DATA_PATH}:/certs"
    env_file:
      - .env

networks:
  default:
    driver: bridge
    name: ${NETWORK_PREFIX}lego
