// Code generated by cmd/gen-dns-registry from internal/dns/providers.yml. DO NOT EDIT.

package main

import (
	"sort"
	"strings"
)

// dnsPlatform describes how this cask addresses one DNS vendor. IDKey,
// SecretKey and ExtKey name the credential this engine puts in each of its
// configuration slots; an empty string means the slot is unused. The keys are
// canonical vendor names -- the runner materialises them under this cask's own
// env prefix, so a hook reads "LEGO" + "_" + key.
type dnsPlatform struct {
	Name      string
	Provider  string
	IDKey     string
	SecretKey string
	ExtKey    string
	Required  []string
}

var dnsPlatforms = map[string]dnsPlatform{
	"alidns":       {Name: "alidns", Provider: "alidns", IDKey: "ALICLOUD_ACCESS_KEY", SecretKey: "ALICLOUD_SECRET_KEY", ExtKey: "", Required: []string{"ALICLOUD_ACCESS_KEY", "ALICLOUD_SECRET_KEY"}},
	"aliesa":       {Name: "aliesa", Provider: "aliesa", IDKey: "ALIESA_ACCESS_KEY", SecretKey: "ALIESA_SECRET_KEY", ExtKey: "", Required: []string{"ALIESA_ACCESS_KEY", "ALIESA_SECRET_KEY"}},
	"baiducloud":   {Name: "baiducloud", Provider: "baiducloud", IDKey: "BAIDUCLOUD_ACCESS_KEY_ID", SecretKey: "BAIDUCLOUD_SECRET_ACCESS_KEY", ExtKey: "", Required: []string{"BAIDUCLOUD_ACCESS_KEY_ID", "BAIDUCLOUD_SECRET_ACCESS_KEY"}},
	"cloudflare":   {Name: "cloudflare", Provider: "cloudflare", IDKey: "", SecretKey: "CLOUDFLARE_DNS_API_TOKEN", ExtKey: "", Required: []string{"CLOUDFLARE_DNS_API_TOKEN"}},
	"cloudns":      {Name: "cloudns", Provider: "cloudns", IDKey: "CLOUDNS_AUTH_ID", SecretKey: "CLOUDNS_AUTH_PASSWORD", ExtKey: "", Required: []string{"CLOUDNS_AUTH_ID", "CLOUDNS_AUTH_PASSWORD"}},
	"dnsla":        {Name: "dnsla", Provider: "dnsla", IDKey: "DNSLA_API_ID", SecretKey: "DNSLA_API_SECRET", ExtKey: "", Required: []string{"DNSLA_API_ID", "DNSLA_API_SECRET"}},
	"dynadot":      {Name: "dynadot", Provider: "dynadot", IDKey: "DYNADOT_API_KEY", SecretKey: "DYNADOT_API_SECRET", ExtKey: "", Required: []string{"DYNADOT_API_KEY", "DYNADOT_API_SECRET"}},
	"edgeone":      {Name: "edgeone", Provider: "edgeone", IDKey: "EDGEONE_SECRET_ID", SecretKey: "EDGEONE_SECRET_KEY", ExtKey: "", Required: []string{"EDGEONE_SECRET_ID", "EDGEONE_SECRET_KEY"}},
	"gcore":        {Name: "gcore", Provider: "gcore", IDKey: "", SecretKey: "GCORE_PERMANENT_API_TOKEN", ExtKey: "", Required: []string{"GCORE_PERMANENT_API_TOKEN"}},
	"godaddy":      {Name: "godaddy", Provider: "godaddy", IDKey: "GODADDY_API_KEY", SecretKey: "GODADDY_API_SECRET", ExtKey: "", Required: []string{"GODADDY_API_KEY", "GODADDY_API_SECRET"}},
	"huaweicloud":  {Name: "huaweicloud", Provider: "huaweicloud", IDKey: "HUAWEICLOUD_ACCESS_KEY_ID", SecretKey: "HUAWEICLOUD_SECRET_ACCESS_KEY", ExtKey: "HUAWEICLOUD_REGION", Required: []string{"HUAWEICLOUD_ACCESS_KEY_ID", "HUAWEICLOUD_REGION", "HUAWEICLOUD_SECRET_ACCESS_KEY"}},
	"namecheap":    {Name: "namecheap", Provider: "namecheap", IDKey: "NAMECHEAP_API_USER", SecretKey: "NAMECHEAP_API_KEY", ExtKey: "", Required: []string{"NAMECHEAP_API_KEY", "NAMECHEAP_API_USER"}},
	"namedotcom":   {Name: "namedotcom", Provider: "namedotcom", IDKey: "NAMECOM_USERNAME", SecretKey: "NAMECOM_API_TOKEN", ExtKey: "", Required: []string{"NAMECOM_API_TOKEN", "NAMECOM_USERNAME"}},
	"namesilo":     {Name: "namesilo", Provider: "namesilo", IDKey: "", SecretKey: "NAMESILO_API_KEY", ExtKey: "", Required: []string{"NAMESILO_API_KEY"}},
	"ns1":          {Name: "ns1", Provider: "ns1", IDKey: "", SecretKey: "NS1_API_KEY", ExtKey: "", Required: []string{"NS1_API_KEY"}},
	"porkbun":      {Name: "porkbun", Provider: "porkbun", IDKey: "PORKBUN_API_KEY", SecretKey: "PORKBUN_SECRET_API_KEY", ExtKey: "", Required: []string{"PORKBUN_API_KEY", "PORKBUN_SECRET_API_KEY"}},
	"rainyun":      {Name: "rainyun", Provider: "rainyun", IDKey: "", SecretKey: "RAINYUN_API_KEY", ExtKey: "", Required: []string{"RAINYUN_API_KEY"}},
	"spaceship":    {Name: "spaceship", Provider: "spaceship", IDKey: "SPACESHIP_API_KEY", SecretKey: "SPACESHIP_API_SECRET", ExtKey: "", Required: []string{"SPACESHIP_API_KEY", "SPACESHIP_API_SECRET"}},
	"tencentcloud": {Name: "tencentcloud", Provider: "tencentcloud", IDKey: "TENCENTCLOUD_SECRET_ID", SecretKey: "TENCENTCLOUD_SECRET_KEY", ExtKey: "", Required: []string{"TENCENTCLOUD_SECRET_ID", "TENCENTCLOUD_SECRET_KEY"}},
	"todaynic":     {Name: "todaynic", Provider: "todaynic", IDKey: "TODAYNIC_AUTH_USER_ID", SecretKey: "TODAYNIC_API_KEY", ExtKey: "", Required: []string{"TODAYNIC_API_KEY", "TODAYNIC_AUTH_USER_ID"}},
	"vercel":       {Name: "vercel", Provider: "vercel", IDKey: "", SecretKey: "VERCEL_API_TOKEN", ExtKey: "VERCEL_TEAM_ID", Required: []string{"VERCEL_API_TOKEN"}},
}

// dnsPlatformAliases maps every accepted spelling to a canonical name.
var dnsPlatformAliases = map[string]string{
	"aliyun":   "alidns",
	"name_com": "namedotcom",
	"namecom":  "namedotcom",
	"nowcn":    "todaynic",
	"nsone":    "ns1",
}

// lookupDNSPlatform resolves a configured platform name, accepting any
// registered alias and treating hyphen and underscore as equivalent.
func lookupDNSPlatform(name string) (dnsPlatform, bool) {
	key := strings.ReplaceAll(strings.ToLower(strings.TrimSpace(name)), "-", "_")
	if canonical, ok := dnsPlatformAliases[key]; ok {
		key = canonical
	}
	p, ok := dnsPlatforms[key]
	return p, ok
}

// supportedDNSPlatforms lists what this cask can address, for error messages.
func supportedDNSPlatforms() []string {
	out := make([]string, 0, len(dnsPlatforms))
	for name := range dnsPlatforms {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}
