package main

import (
	"encoding/json"
	"strings"
	"testing"
)

func baseEnv() map[string]string {
	return map[string]string{
		"AI_AGENT_ENABLED":                 "true",
		"AI_AGENT_DOMAIN_PREFIX":           "agent",
		"AI_AGENT_REPOSITORY_ALLOWLIST":    "anas-project/ANAS",
		"AI_AGENT_RUNTIMES":                "codex",
		"AI_AGENT_RUNTIME_IMAGES":          "codex=" + strings.Repeat("a", 64),
		"AI_AGENT_DB_TYPE":                 "postgres",
		"BASE_DOMAIN":                      "example.test",
		"CONTAINER_PREFIX":                 "anas_",
		"DEFAULT_LANGUAGE":                 "zh-CN",
		"TRAEFIK_BASE_PORT":                "8443",
		computeLeasePrefix + "INTERFACE":   "incus_container",
		computeLeasePrefix + "ENDPOINT":    "https://incus.example:8443",
		computeLeasePrefix + "SANDBOX":     "anas-ai-agent",
		computeLeasePrefix + "CLIENT_CERT": "Y2xpZW50",
		computeLeasePrefix + "CLIENT_KEY":  "a2V5",
	}
}

func runHook(t *testing.T, phase string, env map[string]string, secrets map[string]string) (hookResponse, error) {
	t.Helper()
	if secrets == nil {
		secrets = map[string]string{}
	}
	return handle(hookRequest{
		ABI: "anas.module-hook/v1", Phase: phase, Module: "ai_agent", Env: env, Secrets: secrets,
	})
}

func TestCalculateDerivesDomainAndWebhookURL(t *testing.T) {
	resp, err := runHook(t, "calculate", baseEnv(), nil)
	if err != nil {
		t.Fatalf("calculate: %v", err)
	}
	if got := resp.Env["AI_AGENT_DOMAIN"]; got != "agent.example.test" {
		t.Fatalf("domain = %q", got)
	}
	// The webhook URL is derived, never configured: an operator who could set it
	// could point Forgejo at a host this deployment does not control.
	want := "https://agent.example.test:8443/forgejo/webhook"
	if got := resp.Env["AI_AGENT_WEBHOOK_URL"]; got != want {
		t.Fatalf("webhook URL = %q, want %q", got, want)
	}
	if got := resp.Env["AI_AGENT_FORGEJO_ADMIN_USERNAME"]; got != adminAccount {
		t.Fatalf("administrator = %q, want %q", got, adminAccount)
	}
}

// AGENT-R-009: the signing key is generated by ANAS, not supplied by an
// operator, and it is stable once generated.
func TestCalculateGeneratesAndKeepsSecrets(t *testing.T) {
	resp, err := runHook(t, "calculate", baseEnv(), nil)
	if err != nil {
		t.Fatalf("calculate: %v", err)
	}
	secret := resp.Secrets["AI_AGENT_WEBHOOK_SECRET"]
	password := resp.Secrets["AI_AGENT_FORGEJO_ADMIN_PASSWORD"]
	if len(secret) != 64 || len(password) != 64 {
		t.Fatalf("generated secret/password lengths = %d/%d, want 64 hex characters each", len(secret), len(password))
	}
	if secret == password {
		t.Fatal("the webhook secret and the administrator password are the same value")
	}
	again, err := runHook(t, "calculate", baseEnv(), map[string]string{
		"AI_AGENT_WEBHOOK_SECRET": secret, "AI_AGENT_FORGEJO_ADMIN_PASSWORD": password,
	})
	if err != nil {
		t.Fatalf("second calculate: %v", err)
	}
	if _, regenerated := again.Secrets["AI_AGENT_WEBHOOK_SECRET"]; regenerated {
		t.Fatal("an existing webhook secret was regenerated, which would orphan the registered hook")
	}
}

// AGENT-R-004: `enabled` may not be turned on without every precondition.
func TestEnabledRefusesWithoutItsPreconditions(t *testing.T) {
	for key, want := range map[string]string{
		"AI_AGENT_REPOSITORY_ALLOWLIST":   "AI_AGENT_REPOSITORY_ALLOWLIST",
		"AI_AGENT_RUNTIMES":               "AI_AGENT_RUNTIMES",
		"AI_AGENT_RUNTIME_IMAGES":         "AI_AGENT_RUNTIME_IMAGES",
		computeLeasePrefix + "ENDPOINT":   "compute binding",
		computeLeasePrefix + "CLIENT_KEY": "compute binding",
	} {
		t.Run(key, func(t *testing.T) {
			env := baseEnv()
			delete(env, key)
			_, err := runHook(t, "calculate", env, nil)
			if err == nil {
				t.Fatalf("calculate succeeded with %s missing", key)
			}
			if !strings.Contains(err.Error(), want) {
				t.Fatalf("error %q does not name the missing %q", err, want)
			}
		})
	}
}

// A disabled deployment applies with nothing else configured; that is the state
// a fresh install sits in.
func TestDisabledDeploymentAppliesWithoutPreconditions(t *testing.T) {
	env := baseEnv()
	env["AI_AGENT_ENABLED"] = "false"
	for _, key := range []string{
		"AI_AGENT_REPOSITORY_ALLOWLIST", "AI_AGENT_RUNTIMES", "AI_AGENT_RUNTIME_IMAGES",
		computeLeasePrefix + "ENDPOINT",
	} {
		delete(env, key)
	}
	if _, err := runHook(t, "calculate", env, nil); err != nil {
		t.Fatalf("a disabled deployment failed to apply: %v", err)
	}
}

// AGENT-R-001: an approved runtime is pinned to a fingerprint. A tag would let
// the image change without a configuration change.
func TestRuntimeImagesMustBePinned(t *testing.T) {
	for name, value := range map[string]string{
		"a tag":       "codex=v1.2.3",
		"short":       "codex=" + strings.Repeat("a", 40),
		"no digest":   "codex",
		"unpinned id": "claude_code=" + strings.Repeat("a", 64),
	} {
		t.Run(name, func(t *testing.T) {
			env := baseEnv()
			env["AI_AGENT_RUNTIME_IMAGES"] = value
			if _, err := runHook(t, "calculate", env, nil); err == nil {
				t.Fatalf("calculate accepted image pins %q", value)
			}
		})
	}
}

func TestRepositoryAllowlistIsValidated(t *testing.T) {
	env := baseEnv()
	env["AI_AGENT_REPOSITORY_ALLOWLIST"] = "not-a-repo"
	if _, err := runHook(t, "calculate", env, nil); err == nil {
		t.Fatal("calculate accepted a malformed repository")
	}
}

func TestLanguageFallsBackWithAWarning(t *testing.T) {
	env := baseEnv()
	env["AI_AGENT_LANGUAGE"] = "kl-GL"
	resp, err := runHook(t, "calculate", env, nil)
	if err != nil {
		t.Fatalf("calculate: %v", err)
	}
	if resp.Env["AI_AGENT_LANGUAGE"] != "en" {
		t.Fatalf("language = %q, want the English fallback", resp.Env["AI_AGENT_LANGUAGE"])
	}
	if len(resp.Warnings) == 0 || !strings.Contains(resp.Warnings[0], "kl-GL") {
		t.Fatalf("warnings = %v, want the unsupported value named", resp.Warnings)
	}
}

func TestSupportedLanguageIsKept(t *testing.T) {
	resp, err := runHook(t, "calculate", baseEnv(), nil)
	if err != nil {
		t.Fatalf("calculate: %v", err)
	}
	if resp.Env["AI_AGENT_LANGUAGE"] != "zh-CN" {
		t.Fatalf("language = %q, want the inherited zh-CN", resp.Env["AI_AGENT_LANGUAGE"])
	}
	if len(resp.Warnings) != 0 {
		t.Fatalf("warnings = %v, want none for a supported language", resp.Warnings)
	}
}

func TestRenderEnvRequiresTheDatabaseAndForgejoBinding(t *testing.T) {
	calculated, err := runHook(t, "calculate", baseEnv(), nil)
	if err != nil {
		t.Fatalf("calculate: %v", err)
	}
	env := baseEnv()
	for key, value := range calculated.Env {
		env[key] = value
	}
	for key, value := range calculated.Secrets {
		env[key] = value
	}
	if _, err := runHook(t, "render_env", env, nil); err == nil {
		t.Fatal("render_env succeeded without a database binding")
	}
	for key, value := range map[string]string{
		"AI_AGENT_DB_HOST": "postgres", "AI_AGENT_DB_NAME": "ai_agent",
		"AI_AGENT_DB_USERNAME": "ai_agent", "AI_AGENT_DB_PASSWORD": "secret",
		"AI_AGENT_NETWORK_DB": "anas_db", "TZ": "UTC",
	} {
		env[key] = value
	}
	if _, err := runHook(t, "render_env", env, nil); err == nil {
		t.Fatal("render_env succeeded without FORGEJO_DOMAIN_FULL")
	}
	env["FORGEJO_DOMAIN_FULL"] = "http://git.example"
	if _, err := runHook(t, "render_env", env, nil); err == nil {
		t.Fatal("render_env accepted a plaintext Forgejo URL")
	}
	env["FORGEJO_DOMAIN_FULL"] = "https://git.example.test:8443"
	if _, err := runHook(t, "render_env", env, nil); err != nil {
		t.Fatalf("render_env: %v", err)
	}
}

// AGENT-R-010: the administrator password is passed to the Forgejo entrypoint
// on stdin, and the helper's output is never echoed -- an error that quoted it
// would put the password in the deployment log.
func TestAdminReconciliationNeverEchoesTheHelperOutput(t *testing.T) {
	original := runContainerHelper
	t.Cleanup(func() { runContainerHelper = original })

	var sent []byte
	var argv []string
	runContainerHelper = func(payload []byte, name string, args ...string) ([]byte, error) {
		sent = payload
		argv = append([]string{name}, args...)
		return nil, nil
	}
	env := baseEnv()
	env["AI_AGENT_FORGEJO_ADMIN_PASSWORD"] = "the-administrator-password"
	if err := reconcileAdminAccount(env); err != nil {
		t.Fatalf("reconcileAdminAccount: %v", err)
	}
	var input localAdminInput
	if err := json.Unmarshal(sent, &input); err != nil {
		t.Fatalf("payload is not the managed-account input: %v", err)
	}
	if input.Username != adminAccount || input.Password != "the-administrator-password" {
		t.Fatalf("payload = %+v, want the dedicated administrator", input)
	}
	if strings.Join(argv, " ") != "docker exec -i --user 1000:1000 anas_forgejo /usr/local/bin/anas-forgejo-entrypoint local-admin" {
		t.Fatalf("argv = %v", argv)
	}
	for _, arg := range argv {
		if strings.Contains(arg, "the-administrator-password") {
			t.Fatal("the password was passed as a command-line argument, where every process on the host can read it")
		}
	}

	runContainerHelper = func([]byte, string, ...string) ([]byte, error) {
		return []byte("forgejo said: password the-administrator-password rejected"), errFailed{}
	}
	err := reconcileAdminAccount(env)
	if err == nil {
		t.Fatal("reconcileAdminAccount reported success although the helper failed")
	}
	if strings.Contains(err.Error(), "the-administrator-password") {
		t.Fatalf("the error echoed the password: %q", err)
	}
}

type errFailed struct{}

func (errFailed) Error() string { return "exit status 1" }

func TestAdminReconciliationIsSkippedWhenDisabled(t *testing.T) {
	original := runContainerHelper
	t.Cleanup(func() { runContainerHelper = original })
	called := false
	runContainerHelper = func([]byte, string, ...string) ([]byte, error) {
		called = true
		return nil, nil
	}
	env := baseEnv()
	env["AI_AGENT_ENABLED"] = "false"
	if err := reconcileAdminAccount(env); err != nil {
		t.Fatalf("reconcileAdminAccount: %v", err)
	}
	if called {
		t.Fatal("a disabled deployment still provisioned a Forgejo administrator")
	}
}

func TestCredentialOperationsAreScopedToTheWebhookSecret(t *testing.T) {
	original := credentialDockerInspect
	t.Cleanup(func() { credentialDockerInspect = original })
	credentialDockerInspect = func(string) ([]byte, error) {
		return json.Marshal([]string{"AI_AGENT_WEBHOOK_SECRET=desired-value"})
	}
	req := hookRequest{
		ABI: "anas.module-hook/v1", Phase: "credential_reconcile", Module: "ai_agent",
		Env:     map[string]string{"CONTAINER_PREFIX": "anas_"},
		Secrets: map[string]string{"CANDIDATE": "desired-value"},
		Credential: &credentialOperation{
			Handler: "reconcile-ai-agent-webhook-secret", CredentialID: "ai_agent.webhook_secret",
			SecretKey: "AI_AGENT_WEBHOOK_SECRET", DesiredSecretKey: "CANDIDATE", Authority: "anas",
		},
	}
	resp, err := handle(req)
	if err != nil {
		t.Fatalf("credential_reconcile: %v", err)
	}
	if resp.Credential == nil || resp.Credential.Status != "match" {
		t.Fatalf("credential result = %+v, want a match", resp.Credential)
	}

	// A handler name that belongs to another credential must be refused rather
	// than quietly applied to this one.
	req.Credential.CredentialID = "ai_agent.forgejo_admin_password"
	if _, err := handle(req); err == nil {
		t.Fatal("the hook accepted a credential operation for a different credential")
	}
}

func TestCredentialReconcileRefusesAnExternalAuthority(t *testing.T) {
	original := credentialDockerInspect
	t.Cleanup(func() { credentialDockerInspect = original })
	credentialDockerInspect = func(string) ([]byte, error) {
		return json.Marshal([]string{"AI_AGENT_WEBHOOK_SECRET=desired-value"})
	}
	_, err := handle(hookRequest{
		ABI: "anas.module-hook/v1", Phase: "credential_reconcile", Module: "ai_agent",
		Env:     map[string]string{"CONTAINER_PREFIX": "anas_"},
		Secrets: map[string]string{"CANDIDATE": "desired-value"},
		Credential: &credentialOperation{
			Handler: "reconcile-ai-agent-webhook-secret", CredentialID: "ai_agent.webhook_secret",
			SecretKey: "AI_AGENT_WEBHOOK_SECRET", DesiredSecretKey: "CANDIDATE", Authority: "external",
		},
	})
	if err == nil {
		t.Fatal("the hook reconciled a credential it does not own")
	}
}

func TestOtherModulesAreIgnored(t *testing.T) {
	resp, err := handle(hookRequest{
		ABI: "anas.module-hook/v1", Phase: "calculate", Module: "forgejo", Env: baseEnv(),
	})
	if err != nil {
		t.Fatalf("handle: %v", err)
	}
	if len(resp.Env) != 0 || len(resp.Secrets) != 0 {
		t.Fatalf("the hook acted on another module's request: %+v", resp)
	}
}

// The capability groups the directory has to create are published from the
// enabled runtimes, not written down here, so enabling a runtime creates its
// group and this file names none of them.
func TestCapabilityGroupsFollowTheEnabledRuntimes(t *testing.T) {
	env := baseEnv()
	env["AI_AGENT_RUNTIMES"] = "codex,claude_code"
	env["AI_AGENT_RUNTIME_IMAGES"] = "codex=" + strings.Repeat("a", 64) +
		",claude_code=" + strings.Repeat("b", 64)
	resp, err := runHook(t, "calculate", env, nil)
	if err != nil {
		t.Fatalf("calculate: %v", err)
	}
	groups := splitCSV(resp.Env["ANAS_IDENTITY_CAPABILITY_GROUPS"])
	for _, want := range []string{
		"ai_agent_execute", "ai_agent_terminal", "ai_agent_codex", "ai_agent_claude_code",
	} {
		if !containsString(groups, want) {
			t.Errorf("groups = %v, missing %q", groups, want)
		}
	}
	if containsString(groups, "ai_agent_pi") {
		t.Fatalf("groups = %v; a runtime that is not enabled got a group", groups)
	}
}

// The module appends to the deployment-wide list instead of replacing it, the
// same way an application appends itself to APPS_LIST.
func TestCapabilityGroupsAppendToWhatOtherModulesPublished(t *testing.T) {
	env := baseEnv()
	env["ANAS_IDENTITY_CAPABILITY_GROUPS"] = "nextcloud_admin,ai_agent_execute"
	resp, err := runHook(t, "calculate", env, nil)
	if err != nil {
		t.Fatalf("calculate: %v", err)
	}
	groups := splitCSV(resp.Env["ANAS_IDENTITY_CAPABILITY_GROUPS"])
	if !containsString(groups, "nextcloud_admin") {
		t.Fatalf("groups = %v; another module's entry was dropped", groups)
	}
	// An entry already present is not repeated.
	count := 0
	for _, group := range groups {
		if group == "ai_agent_execute" {
			count++
		}
	}
	if count != 1 {
		t.Fatalf("groups = %v; ai_agent_execute appears %d times", groups, count)
	}
}

// A disabled deployment publishes no groups: a group nobody can use is one an
// administrator has to wonder about.
func TestDisabledDeploymentPublishesNoCapabilityGroups(t *testing.T) {
	env := baseEnv()
	env["AI_AGENT_ENABLED"] = "false"
	resp, err := runHook(t, "calculate", env, nil)
	if err != nil {
		t.Fatalf("calculate: %v", err)
	}
	if value, present := resp.Env["ANAS_IDENTITY_CAPABILITY_GROUPS"]; present && value != "" {
		t.Fatalf("a disabled deployment published %q", value)
	}
}

func containsString(values []string, wanted string) bool {
	for _, value := range values {
		if value == wanted {
			return true
		}
	}
	return false
}
