package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
)

const hookABI = "anas.cask/v1"

type hookRequest struct {
	ABI     string            `json:"abi"`
	Phase   string            `json:"phase"`
	Module  string            `json:"module"`
	Workdir string            `json:"workdir"`
	Env     map[string]string `json:"env"`
	Secrets map[string]string `json:"secrets"`
}

type hookResponse struct {
	Env             map[string]string `json:"env,omitempty"`
	Secrets         map[string]string `json:"secrets,omitempty"`
	Files           map[string]string `json:"files,omitempty"`
	DisableServices []string          `json:"disable_services,omitempty"`
	DockerCopies    []dockerCopy      `json:"docker_copies,omitempty"`
}

type dockerCopy struct {
	Source      string `json:"source"`
	Container   string `json:"container"`
	Destination string `json:"destination"`
}

type secretStore struct {
	values map[string]string
}

func (s *secretStore) Ensure(key string, gen func() (string, error)) (string, error) {
	if v := s.values[key]; v != "" {
		return v, nil
	}
	v, err := gen()
	if err != nil {
		return "", err
	}
	s.values[key] = v
	return v, nil
}

func main() {
	b, err := io.ReadAll(os.Stdin)
	if err != nil {
		fail(err)
	}
	var req hookRequest
	if err := json.Unmarshal(b, &req); err != nil {
		fail(err)
	}
	if req.ABI != hookABI {
		fail(fmt.Errorf("unsupported ABI %q", req.ABI))
	}
	resp, err := handle(req)
	if err != nil {
		fail(err)
	}
	if resp.Env == nil {
		resp.Env = map[string]string{}
	}
	if resp.Secrets == nil {
		resp.Secrets = map[string]string{}
	}
	out, err := json.Marshal(resp)
	if err != nil {
		fail(err)
	}
	fmt.Print(string(out))
}
func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
func handle(req hookRequest) (hookResponse, error) {
	env := cloneMap(req.Env)
	secrets := &secretStore{values: cloneMap(req.Secrets)}
	switch req.Phase {
	case "calculate":
		if err := calculate(req.Module, env, req.Workdir, secrets); err != nil {
			return hookResponse{}, err
		}
		return hookResponse{Env: changed(req.Env, env), Secrets: changed(req.Secrets, secrets.values)}, nil
	case "render_env":
		files, err := renderEnv(req.Module, env, req.Workdir)
		if err != nil {
			return hookResponse{}, err
		}
		return hookResponse{Env: changed(req.Env, env), Files: files}, nil
	case "services":
		return hookResponse{DisableServices: disabledServices(req.Module, env)}, nil
	case "after_start":
		return hookResponse{DockerCopies: afterStart(req.Module, env)}, nil
	default:
		return hookResponse{}, nil
	}
}
func calculate(module string, env map[string]string, workdir string, secrets *secretStore) error {
	if module != "postgres" {
		return nil
	}
	return calcPostgres(env, workdir, secrets)
}
func renderEnv(module string, env map[string]string, workdir string) (map[string]string, error) {
	if module != "postgres" {
		return map[string]string{}, nil
	}
	env["POSTGRES_HOST_AUTH_METHOD"] = "trust"
	env["ADMINER_DESIGN"] = "nette"
	files := map[string]string{}
	if script := initDatabasesScript(env); script != "" {
		files["initdb/10-anas-create-databases.sh"] = script
	}
	return files, nil
}

// dependentDatabases returns the databases that other enabled modules expect to
// exist on this PostgreSQL instance. A module declares its database with
// <PREFIX>_DB_NAME and points at a host with <PREFIX>_DB_HOST or
// <PREFIX>_NETWORK_DB. Only databases whose host resolves to this postgres
// service are provisioned here, so MariaDB-backed modules are left untouched.
func dependentDatabases(env map[string]string) []string {
	host := env["POSTGRES_HOST"]
	if host == "" {
		return nil
	}
	own := env["POSTGRES_USER"]
	seen := map[string]bool{}
	var dbs []string
	for key, name := range env {
		if name == "" || !strings.HasSuffix(key, "_DB_NAME") {
			continue
		}
		prefix := strings.TrimSuffix(key, "_DB_NAME")
		if env[prefix+"_DB_HOST"] != host && env[prefix+"_NETWORK_DB"] != host {
			continue
		}
		if name == own || seen[name] {
			continue
		}
		seen[name] = true
		dbs = append(dbs, name)
	}
	sort.Strings(dbs)
	return dbs
}

// initDatabasesScript renders an idempotent /docker-entrypoint-initdb.d script
// that creates each dependent database if it does not already exist. Returns an
// empty string when there is nothing to create.
func initDatabasesScript(env map[string]string) string {
	dbs := dependentDatabases(env)
	if len(dbs) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Auto-generated by the anas postgres cask. Do not edit.\n")
	b.WriteString("# Creates databases required by dependent modules on first init.\n")
	b.WriteString("set -eu\n\n")
	b.WriteString("for db in " + strings.Join(dbs, " ") + "; do\n")
	b.WriteString("  exists=$(psql --username \"$POSTGRES_USER\" -tAc \"SELECT 1 FROM pg_database WHERE datname='$db'\")\n")
	b.WriteString("  if [ \"$exists\" = \"1\" ]; then\n")
	b.WriteString("    echo \"anas: database $db already exists\"\n")
	b.WriteString("  else\n")
	b.WriteString("    echo \"anas: creating database $db\"\n")
	b.WriteString("    psql --username \"$POSTGRES_USER\" -c \"CREATE DATABASE \\\"$db\\\"\"\n")
	b.WriteString("  fi\n")
	b.WriteString("done\n")
	return b.String()
}
func disabledServices(module string, env map[string]string) []string {
	if module != "postgres" {
		return nil
	}
	if env["POSTGRES_ADMINER_ENABLED"] != "true" {
		return []string{"postgres_adminer", "anas_postgres_adminer"}
	}
	return nil
}
func afterStart(module string, env map[string]string) []dockerCopy {
	if module != "postgres" {
		return nil
	}
	return nil
}
func cloneMap(in map[string]string) map[string]string {
	out := map[string]string{}
	for k, v := range in {
		out[k] = v
	}
	return out
}
func changed(old, cur map[string]string) map[string]string {
	out := map[string]string{}
	for k, v := range cur {
		if old[k] != v {
			out[k] = v
		}
	}
	return out
}
func calcPostgres(e map[string]string, _ string, _ *secretStore) error {
	e["POSTGRES_NETWORK_NAME"] = defaultValue(e["POSTGRES_NETWORK_NAME"], e["NETWORK_PREFIX"]+"postgres")
	e["POSTGRES_PASSWORD"] = defaultValue(e["POSTGRES_PASSWORD"], e["DEFAULT_SERVICE_ROOT_PASSWORD"])
	e["POSTGRES_USER"] = e["POSTGRES_USERNAME"]
	e["POSTGRES_HOST"] = e["CONTAINER_PREFIX"] + "postgres"
	e["POSTGRES_PORT"] = "5432"
	e["POSTGRES_HOST_PORT"] = e["POSTGRES_HOST"] + ":" + e["POSTGRES_PORT"]
	e["POSTGRES_ADMINER_DOMAIN_PREFIX"] = defaultValue(e["POSTGRES_ADMINER_DOMAIN_PREFIX"], "postgres_adminer")
	e["POSTGRES_ADMINER_DOMAIN"] = e["POSTGRES_ADMINER_DOMAIN_PREFIX"] + "." + e["BASE_DOMAIN"]
	return nil
}
func defaultValue(v, d string) string {
	if v == "" {
		return d
	}
	return v
}
