package main

// renderDirectoryBlueprint deliberately contains no deployment values or
// credentials. Those are calculated from samba_dc's exported environment and
// resolved by authentik's !Env tag when it applies the blueprint.
func renderDirectoryBlueprint() string {
	return `# Auto-generated by the anas authentik module. Do not edit.
version: 1
metadata:
  name: anas-samba-ad
entries:
  # Keep authentik's local preflight aligned with Samba's authoritative
  # minimum length. AD complexity is checked separately by authentik's LDAP
  # password validator, which reads pwdProperties and implements the actual
  # three-of-five rule. zxcvbn stays off here so authentik does not invent a
  # second password policy that Samba itself would accept.
  - model: authentik_policies_password.passwordpolicy
    identifiers:
      name: default-password-change-password-policy
    id: samba-ad-password-policy
    attrs:
      password_field: password
      check_static_rules: true
      check_zxcvbn: false
      length_min: !Env AUTHENTIK_PASSWORD_MIN_LENGTH
      amount_digits: 0
      amount_uppercase: 0
      amount_lowercase: 0
      amount_symbols: 0
      error_message: !Env AUTHENTIK_PASSWORD_POLICY_ERROR

  - model: authentik_stages_prompt.prompt
    identifiers:
      name: anas Samba AD password policy guidance
    id: samba-ad-password-policy-guidance
    attrs:
      order: 250
      field_key: anas_password_policy_guidance
      type: alert_info
      required: false
      label: Password requirements
      placeholder: !Env AUTHENTIK_PASSWORD_POLICY_GUIDANCE
      initial_value: !Env AUTHENTIK_PASSWORD_POLICY_GUIDANCE

  - model: authentik_stages_prompt.promptstage
    identifiers:
      name: default-password-change-prompt
    attrs:
      fields:
        - !KeyOf samba-ad-password-policy-guidance
        - !Find [authentik_stages_prompt.prompt, [name, "default-password-change-field-password"]]
        - !Find [authentik_stages_prompt.prompt, [name, "default-password-change-field-password-repeat"]]
      validation_policies:
        - !KeyOf samba-ad-password-policy

  - model: authentik_sources_ldap.ldapsourcepropertymapping
    identifiers:
      name: anas Samba AD display name mapping
    id: samba-ad-user-display-name-mapping
    attrs:
      expression: |
        display_name = list_flatten(ldap.get("displayName"))
        if not display_name:
            display_name = list_flatten(ldap.get("cn"))
        return {"name": display_name}

  # A small NAS uses Samba AD's exact Admins group as its single management
  # role. All other synchronized groups remain non-superuser groups.
  - model: authentik_sources_ldap.ldapsourcepropertymapping
    identifiers:
      name: anas Samba AD group role mapping
    id: samba-ad-group-role-mapping
    attrs:
      expression: |
        group_name = list_flatten(ldap.get("cn"))
        return {
            "name": group_name,
            "is_superuser": group_name == "Admins",
        }

  - model: authentik_sources_ldap.ldapsource
    identifiers:
      slug: samba-ad
    attrs:
      name: Samba AD
      enabled: true
      server_uri: !Env AUTHENTIK_LDAP_SERVER_URI
      peer_certificate: !Find [authentik_crypto.certificatekeypair, [name, "anas-samba-ad-ca"]]
      bind_cn: !Env AUTHENTIK_LDAP_BIND_DN
      bind_password: !Env AUTHENTIK_LDAP_BIND_PASSWORD
      base_dn: !Env AUTHENTIK_LDAP_BASE_DN
      additional_user_dn: !Env AUTHENTIK_LDAP_ADDITIONAL_USER_DN
      additional_group_dn: !Env AUTHENTIK_LDAP_ADDITIONAL_GROUP_DN
      user_object_filter: !Env AUTHENTIK_LDAP_USER_OBJECT_FILTER
      group_object_filter: !Env AUTHENTIK_LDAP_GROUP_OBJECT_FILTER
      object_uniqueness_field: !Env AUTHENTIK_LDAP_OBJECT_UNIQUENESS_FIELD
      lookup_groups_from_user: true
      group_membership_field: !Env AUTHENTIK_LDAP_GROUP_MEMBERSHIP_FIELD
      user_membership_attribute: !Env AUTHENTIK_LDAP_USER_MEMBERSHIP_ATTRIBUTE
      sync_users: true
      sync_groups: true
      sync_users_password: !Env AUTHENTIK_LDAP_PASSWORD_WRITEBACK
      password_login_update_internal_password: false
      delete_not_found_objects: true
      authentication_flow: !Find [authentik_flows.flow, [slug, default-source-authentication]]
      enrollment_flow: !Find [authentik_flows.flow, [slug, default-source-enrollment]]
      user_property_mappings:
        - !Find [authentik_sources_ldap.ldapsourcepropertymapping, [name, "authentik default Active Directory Mapping: givenName"]]
        - !Find [authentik_sources_ldap.ldapsourcepropertymapping, [name, "authentik default Active Directory Mapping: sAMAccountName"]]
        - !Find [authentik_sources_ldap.ldapsourcepropertymapping, [name, "authentik default Active Directory Mapping: sn"]]
        - !Find [authentik_sources_ldap.ldapsourcepropertymapping, [name, "authentik default Active Directory Mapping: userPrincipalName"]]
        - !Find [authentik_sources_ldap.ldapsourcepropertymapping, [name, "authentik default LDAP Mapping: mail"]]
        - !KeyOf samba-ad-user-display-name-mapping
      group_property_mappings:
        - !KeyOf samba-ad-group-role-mapping

  # Keep the inbuilt backend solely for the sealed akadmin break-glass user;
  # every synchronized business user has an unusable local password and is
  # authenticated through Samba AD by the LDAP backend.
  - model: authentik_stages_password.passwordstage
    identifiers:
      name: default-authentication-password
    attrs:
      backends:
        - authentik.core.auth.InbuiltBackend
        - authentik.sources.ldap.auth.LDAPBackend
`
}
