// Code generated by cmd/gen-dns-registry from internal/dns/providers.yml. DO NOT EDIT.

package main

import (
	"sort"
	"strings"
)

// dnsPlatform describes how this cask addresses one DNS vendor. IDKey,
// SecretKey and ExtKey name the credential this engine puts in each of its
// configuration slots; an empty string means the slot is unused. The keys are
// canonical vendor names -- the runner materialises them under this cask's own
// env prefix, so a hook reads "DDNS_UPDATER" + "_" + key.
type dnsPlatform struct {
	Name      string
	Provider  string
	IDKey     string
	SecretKey string
	ExtKey    string
	Required  []string
}

var dnsPlatforms = map[string]dnsPlatform{
	"alidns":     {Name: "alidns", Provider: "aliyun", IDKey: "ALICLOUD_ACCESS_KEY", SecretKey: "ALICLOUD_SECRET_KEY", ExtKey: "", Required: []string{"ALICLOUD_ACCESS_KEY", "ALICLOUD_SECRET_KEY"}},
	"cloudflare": {Name: "cloudflare", Provider: "cloudflare", IDKey: "", SecretKey: "CLOUDFLARE_DNS_API_TOKEN", ExtKey: "", Required: []string{"CLOUDFLARE_DNS_API_TOKEN"}},
	"godaddy":    {Name: "godaddy", Provider: "godaddy", IDKey: "GODADDY_API_KEY", SecretKey: "GODADDY_API_SECRET", ExtKey: "", Required: []string{"GODADDY_API_KEY", "GODADDY_API_SECRET"}},
	"namecheap":  {Name: "namecheap", Provider: "namecheap", IDKey: "", SecretKey: "NAMECHEAP_DDNS_PASSWORD", ExtKey: "", Required: []string{"NAMECHEAP_DDNS_PASSWORD"}},
	"namedotcom": {Name: "namedotcom", Provider: "namecom", IDKey: "NAMECOM_USERNAME", SecretKey: "NAMECOM_API_TOKEN", ExtKey: "", Required: []string{"NAMECOM_API_TOKEN", "NAMECOM_USERNAME"}},
	"namesilo":   {Name: "namesilo", Provider: "namesilo", IDKey: "", SecretKey: "NAMESILO_API_KEY", ExtKey: "", Required: []string{"NAMESILO_API_KEY"}},
	"porkbun":    {Name: "porkbun", Provider: "porkbun", IDKey: "PORKBUN_API_KEY", SecretKey: "PORKBUN_SECRET_API_KEY", ExtKey: "", Required: []string{"PORKBUN_API_KEY", "PORKBUN_SECRET_API_KEY"}},
	"spaceship":  {Name: "spaceship", Provider: "spaceship", IDKey: "SPACESHIP_API_KEY", SecretKey: "SPACESHIP_API_SECRET", ExtKey: "", Required: []string{"SPACESHIP_API_KEY", "SPACESHIP_API_SECRET"}},
}

// dnsPlatformAliases maps every accepted spelling to a canonical name.
var dnsPlatformAliases = map[string]string{
	"aliyun":   "alidns",
	"name_com": "namedotcom",
	"namecom":  "namedotcom",
}

// lookupDNSPlatform resolves a configured platform name, accepting any
// registered alias and treating hyphen and underscore as equivalent.
func lookupDNSPlatform(name string) (dnsPlatform, bool) {
	key := strings.ReplaceAll(strings.ToLower(strings.TrimSpace(name)), "-", "_")
	if canonical, ok := dnsPlatformAliases[key]; ok {
		key = canonical
	}
	p, ok := dnsPlatforms[key]
	return p, ok
}

// supportedDNSPlatforms lists what this cask can address, for error messages.
func supportedDNSPlatforms() []string {
	out := make([]string, 0, len(dnsPlatforms))
	for name := range dnsPlatforms {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}
