package main

// renderDirectoryBlueprint deliberately contains no deployment values or
// credentials. Those are calculated from samba_dc's exported environment and
// resolved by authentik's !Env tag when it applies the blueprint.
func renderDirectoryBlueprint() string {
	return `# Auto-generated by the anas authentik cask. Do not edit.
version: 1
metadata:
  name: anas-samba-ad
entries:
  # A small NAS uses Samba AD's exact Admins group as its single management
  # role. All other synchronized groups remain non-superuser groups.
  - model: authentik_sources_ldap.ldapsourcepropertymapping
    identifiers:
      name: anas Samba AD group role mapping
    id: samba-ad-group-role-mapping
    attrs:
      expression: |
        group_name = list_flatten(ldap.get("cn"))
        return {
            "name": group_name,
            "is_superuser": group_name == "Admins",
        }

  - model: authentik_sources_ldap.ldapsource
    identifiers:
      slug: samba-ad
    attrs:
      name: Samba AD
      enabled: true
      server_uri: !Env AUTHENTIK_LDAP_SERVER_URI
      peer_certificate: !Find [authentik_crypto.certificatekeypair, [name, "anas-samba-ad-ca"]]
      bind_cn: !Env AUTHENTIK_LDAP_BIND_DN
      bind_password: !Env AUTHENTIK_LDAP_BIND_PASSWORD
      base_dn: !Env AUTHENTIK_LDAP_BASE_DN
      additional_user_dn: !Env AUTHENTIK_LDAP_ADDITIONAL_USER_DN
      additional_group_dn: !Env AUTHENTIK_LDAP_ADDITIONAL_GROUP_DN
      user_object_filter: !Env AUTHENTIK_LDAP_USER_OBJECT_FILTER
      group_object_filter: !Env AUTHENTIK_LDAP_GROUP_OBJECT_FILTER
      object_uniqueness_field: !Env AUTHENTIK_LDAP_OBJECT_UNIQUENESS_FIELD
      lookup_groups_from_user: true
      group_membership_field: !Env AUTHENTIK_LDAP_GROUP_MEMBERSHIP_FIELD
      user_membership_attribute: !Env AUTHENTIK_LDAP_USER_MEMBERSHIP_ATTRIBUTE
      sync_users: true
      sync_groups: true
      sync_users_password: !Env AUTHENTIK_LDAP_PASSWORD_WRITEBACK
      password_login_update_internal_password: false
      delete_not_found_objects: true
      authentication_flow: !Find [authentik_flows.flow, [slug, default-source-authentication]]
      enrollment_flow: !Find [authentik_flows.flow, [slug, default-source-enrollment]]
      user_property_mappings:
        - !Find [authentik_sources_ldap.ldapsourcepropertymapping, [name, "authentik default Active Directory Mapping: givenName"]]
        - !Find [authentik_sources_ldap.ldapsourcepropertymapping, [name, "authentik default Active Directory Mapping: sAMAccountName"]]
        - !Find [authentik_sources_ldap.ldapsourcepropertymapping, [name, "authentik default Active Directory Mapping: sn"]]
        - !Find [authentik_sources_ldap.ldapsourcepropertymapping, [name, "authentik default Active Directory Mapping: userPrincipalName"]]
        - !Find [authentik_sources_ldap.ldapsourcepropertymapping, [name, "authentik default LDAP Mapping: mail"]]
        - !Find [authentik_sources_ldap.ldapsourcepropertymapping, [name, "authentik default LDAP Mapping: Name"]]
      group_property_mappings:
        - !KeyOf samba-ad-group-role-mapping

  # Keep the inbuilt backend solely for the sealed akadmin break-glass user;
  # every synchronized business user has an unusable local password and is
  # authenticated through Samba AD by the LDAP backend.
  - model: authentik_stages_password.passwordstage
    identifiers:
      name: default-authentication-password
    attrs:
      backends:
        - authentik.core.auth.InbuiltBackend
        - authentik.sources.ldap.auth.LDAPBackend
`
}
